# Site settings
title: "Tim Klapdor"
email: tim.klapdor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the resume of Tim Klapdor. Tim trained as a graphic designer and has been working in higher education, originally developing eLearning resources but is now focussed on the underlying technology used in education.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: timklapdor
github_username:  timklapdor


# Collections
collections:
    award:
        output: true
        title: Award
    education: 
        output: true
        title: Education
    experience:
        output: true
        title: Experience
    interests:
        output: true
        title: Interest
    portfolio:
        output: true
        title: Potrtfolio
    publications:
        output: true
        title: Publication
    profile:
        output: true
    title: Profile

# Build settings
markdown: kramdown
highlighter: pygments

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
