# Site settings
title: "Tim Klapdor" # your name
description: "Technology | Design | Education" # your personal tagline 
header-img: images/tim-hd.jpg # image in header
twitter_name: timklapdor # your twitter handle
github_name:  timklapdor # your github name
baseurl: "/resume-builder" # "" base url
url:  # "http://yourdomainin.com"

collections:
    education: 
        output: true
        title: Education
    experience:
        output: true
        title: Experience
    interests:
        output: true
        title: Interest
    portfolio:
        output: true
        title: Potrtfolio
    publications:
        output: true
        title: Publication
    profile:
        output: true
        title: Profile

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
