# Site settings
name: "Tim Klapdor" # your name
description: "Technology | Design | Education" # your personal tagline 
header-img: images/tim-hd.jpg # image in header
city: Wagga Wagga # your city
country: Australia # your country
email: tim.klapdor@gmail.com # your email address
twitter_name: timklapdor # your twitter handle
github_name:  timklapdor # your github name
baseurl: # "" base url
url: # "http://yourdomain.com"

collection:
 - education: 
 - experience:
 - interests:
 - portfolio:
 - publications:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
